[package]
name = "simple_linked_list"
version = "0.1.0"
authors = ["Jason Younker <jason@ynkr.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
